### ISSUE TITLE
Prompt stuck on screen

### ISSUE THREAD

**Issue by vurtss** [Nyemse/SPEARHEAD#184]
When you pick up a gun the prompt is stuck on your screen till you hover over another dropped gun.

  19:13:19.803  Players.USERNAME.PlayerScripts.SPH_Player.ProximityPrompt:204: attempt to index nil with 'Parent'  -  Client - ProximityPrompt:204
  19:13:19.803  Stack Begin  -  Studio
  19:13:19.803  Script 'Players.USERNAME.PlayerScripts.SPH_Player.ProximityPrompt', Line 204  -  Studio - ProximityPrompt:204
  19:13:19.803  Stack End  -  Studio

**Comment by DeletedArch** [comment]
starting from line 204 replace the rest of the code with:
`else
		if prompt.Parent == nil then
			PickUpUI.Visible = false
		elseif prompt.Parent.Parent:FindFirstChild("PickupHighlight") then
			prompt.Parent.Parent.PickupHighlight.Enabled = false
			PickUpUI.Visible = false
		end
	end
end)`

Don't rely on this solution too much it is just a quick fix, I don't know if there is any possible issues with it

![image_2023-12-27_191148640](https://github.com/Nyemse/SPEARHEAD/assets/35235801/5eca2809-71f5-4606-885d-6d21f9b00cba)
